[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "termdo-tasks-api"
version = "1.0.0"
description = "Manages task operations including create update delete and retrieval for user todos"
authors = [{ name = "Emrecan Karaçayır", email = "developer@karacayir.com" }]
license = { text = "MIT" }
readme = "README.md"
dependencies = ["fastapi[standard]"]

[project.optional-dependencies]
dev = ["black", "flake8", "pytest", "pytest-cov"]

[project.urls]
Repository = "https://github.com/termdo-inc/termdo-tasks-api"
Issues = "https://github.com/termdo-inc/termdo-tasks-api/issues"

[tool.setuptools]
package-dir = { "" = "source" }

[tool.pytest.ini_options]
testpaths = "tests"
pythonpath = "source"
addopts = ["--cov=source", "--cov-report=term-missing"]

[tool.black]
line-length = 100
